# Generated by Django 3.0.1 on 2020-02-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True, verbose_name='Updated at')),
                ('created_by', models.CharField(blank=True, db_column='created_by', default='', max_length=100, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, db_column='modified_by', default='', max_length=100, null=True, verbose_name='Updated by')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country Name')),
                ('name_slug', models.SlugField(blank=True, max_length=280, null=True, verbose_name='Country Slug Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Country Description')),
                ('area', models.IntegerField(blank=True, default=0, null=True, verbose_name='Country Area')),
                ('population', models.IntegerField(blank=True, default=0, null=True, verbose_name='Country Population')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified_at', null=True, verbose_name='Updated at')),
                ('created_by', models.CharField(blank=True, db_column='created_by', default='', max_length=100, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, db_column='modified_by', default='', max_length=100, null=True, verbose_name='Updated by')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rank', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, null=True, verbose_name='Rank')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-Mail')),
                ('point', models.IntegerField(blank=True, default=0, null=True, verbose_name='Point')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_system.Country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
